function validate_dmac_config(plant, dmac)
%VALIDATE_DMAC_CONFIG Sanity-check plant/dmac struct consistency.
%
%   VALIDATE_DMAC_CONFIG(plant, dmac) throws an error if the plant and
%   dmac configuration structs are dimensionally or structurally
%   inconsistent. Intended to be called once at the start of the
%   simulation, right after CONFIG_PLANT / CONFIG_DMAC.
%
%   Checks performed:
%     - dmac.{lxi,lu,ly} match plant.{lxi,lu,ly}
%     - plant.C_xi is (lxi x lx)
%     - dmac.Cy_xi is (ly x lxi)
%     - dmac.Cy_xi * plant.C_xi == plant.C, i.e. the tracked output is
%       recoverable from the measured state alone (this is what makes
%       the integral-action augmentation in DMAC_SYNTHESIZE_GAIN valid)
%     - dmac.R0 is sized (lxi+lu) x (lxi+lu)  [RLS regressor dimension]
%     - dmac.Q  is sized (lxi+ly) x (lxi+ly)  [augmented LQR state dimension]
%
%   See also: CONFIG_PLANT, CONFIG_DMAC

assert(isequal(dmac.lxi, plant.lxi), ...
    'validate_dmac_config:dimMismatch', ...
    'dmac.lxi (%d) must match plant.lxi (%d).', dmac.lxi, plant.lxi);
assert(isequal(dmac.lu, plant.lu), ...
    'validate_dmac_config:dimMismatch', ...
    'dmac.lu (%d) must match plant.lu (%d).', dmac.lu, plant.lu);
assert(isequal(dmac.ly, plant.ly), ...
    'validate_dmac_config:dimMismatch', ...
    'dmac.ly (%d) must match plant.ly (%d).', dmac.ly, plant.ly);

assert(isequal(size(plant.C_xi), [plant.lxi, plant.lx]), ...
    'validate_dmac_config:dimMismatch', ...
    'plant.C_xi must be size (lxi x lx) = (%d x %d).', plant.lxi, plant.lx);

assert(isequal(size(dmac.Cy_xi), [plant.ly, plant.lxi]), ...
    'validate_dmac_config:dimMismatch', ...
    'dmac.Cy_xi must be size (ly x lxi) = (%d x %d).', plant.ly, plant.lxi);

C_check = dmac.Cy_xi * plant.C_xi;
if norm(C_check - plant.C, 'fro') > 1e-9
    error('validate_dmac_config:inconsistentOutputMap', ...
        ['dmac.Cy_xi * plant.C_xi must equal plant.C: the tracked ' ...
         'output y_k must be recoverable from the measured state ' ...
         'xi_k alone. Got a mismatch of norm %.3g.'], ...
        norm(C_check - plant.C, 'fro'));
end

expected_R0_size = dmac.lxi + dmac.lu;
assert(isequal(size(dmac.R0), [expected_R0_size, expected_R0_size]), ...
    'validate_dmac_config:dimMismatch', ...
    'dmac.R0 must be size (lxi+lu) x (lxi+lu) = (%d x %d).', ...
    expected_R0_size, expected_R0_size);

if strcmp(dmac.integrator, 'yes')
    % Q sizes the augmented [xi; q] state used by idare in
    % dmac_synthesize_gain; q has dimension ly, not lu.
    expected_Q_size = dmac.lxi + dmac.ly;
    assert(isequal(size(dmac.Q), [expected_Q_size, expected_Q_size]), ...
        'validate_dmac_config:dimMismatch', ...
        'dmac.Q must be size (lxi+ly) x (lxi+ly) = (%d x %d) when using integral action.', ...
        expected_Q_size, expected_Q_size);
end
end